### ISSUE TITLE
Chess challenge

### ISSUE THREAD

**Issue by a97antonio** [fraz3alpha/running-challenges#133]
Possible Chess challenge - run at 
2 Castles  eg Clitheroe Castle, Sheffield Castle
2 Racecources eg York, Pontefract
2 Religious interest sites eg Fountains Abbey, Nostell Priory
1 Queen eg Queen Elizabeth, Queens
1 King eg Kingsbury Water, Woking

**Comment by JohnRBuchanan** [comment]
Great idea but I would add the need for 8 Ps (Pawns)

**Comment by itsafrogslife** [comment]
Challenges can only work using particular letter combinations in the official name of a parkrun. That's why Lowestoft and Oswestry count as a 'west' in the compass challenge but Milano Nord doesn't count as a 'north'. This means that finding all the 'castles' is easy, but finding all the racecourses can't be done without maintaining a separate list (i.e. extra work...!).

**Comment by josh-justjosh** [comment]
There are four parkruns with racecourse in their name:

- Bourke Racecourse parkrun (AU),

- Wexford Racecourse parkrun (IE),

- Broken Hill Racecourse parkrun (AU) and

- Market Rasen Racecourse parkrun (Lincolnshire, UK)
so not impossibe?

**Comment by itsafrogslife** [comment]
> There are four parkruns with racecourse in their name:
> 
> * Bourke Racecourse parkrun (AU),
> * Wexford Racecourse parkrun (IE),
> * Broken Hill Racecourse parkrun (AU) and
> * Market Rasen Racecourse parkrun (Lincolnshire, UK)
>   so not impossibe?

It's possible, but would likely upset the other parkruns run on or next to racecourses that don't have 'racecourse' in the name.

**Comment by a97antonio** [comment]
Great call, keeping it simple is the best way. Cheers for considering it.
