### ISSUE TITLE
Extension failing to load event data

### ISSUE THREAD

**Issue by rboyatt** [fraz3alpha/running-challenges#210]
The extension is failing to load correctly, reporting a problem loading event location and event status data - this prevents some of the challenges from loading correctly.

![image](https://user-images.githubusercontent.com/900659/71326899-035b6780-24f9-11ea-95f7-f407a56e5ec7.png)

**Comment by fraz3alpha** [comment]
We noticed it doing this this week - we think that there might be a permissions change in the browser, or something else needs changing. We are going to take a look this week when we can around Christmas things :)

**Comment by fraz3alpha** [comment]
@rboyatt , great spot with that PR - they must have stopped generating that column in the wiki at some point recently, and now it breaks the whole background page. 

If you weren't aware of it, there is a "testing" page where you can clear the cached data so you can simulate what happens when there is no old geo data etc.. - chrome-extension://ahcffjfhfdpapbiajdbimjjgglebbaph/html/testing.html (that ID might change, so click the "options" link in the main athlete page to get to that page, and replace "options" with "testing".

I've done that, and your PR seems to fix things, so I'll merge it - thanks!

**Comment by fraz3alpha** [comment]
v0.7.8 has been pushed to the Chrome and Firefox stores, it should be available shortly

**Comment by rboyatt** [comment]
Not clear from wiki history as it includes another page but possible changes on Thursday 19th.  And thanks for info on testing page- wasn't aware of that, will use that next time!
