### ISSUE TITLE
junior parkruns not being counted in some stats

### ISSUE THREAD

**Issue by josh-justjosh** [fraz3alpha/running-challenges#236]
I noticed while checking #235 that junior parkruns don't seem to be counted/included in the following statistics:

- Average parkrun lat/lon location
- Countries visited

Perhaps for people under 14, there could be an extra row for average junior parkrun event

**Comment by fraz3alpha** [comment]
Until we switched to events.json (#197) the extension didn't have the locations of the junior events as they were stored in a separate file on the parkrun website that we didn't pull down. This necessarily meant that anything that required knowing *where* a junior parkrun was skipped.

The events JSON file *does* now have them in, but the code within the extension effectively ignores them completely as there is no current mechanism to parse those event and consider different event types where necessary (e.g. the explorer map). Of course anything that just looks at the parkrun name works - as that doesn't need the location - e.g. tourism, alphabeteer etc.., and the volunteer information on the parkrun website doesn't differentiate as to where you volunteered - so that's already combined information.

We are generally of the opinion that they should count as much as a regular parkrun, i.e. not be differentiated as junior/5k stats, and just be one "parkrun", so yes, eventually we'll come back and look at how to fold in junior parkrun properly and get it fully supported.
