### ISSUE TITLE
Ideas for challenges not based around tourism

### ISSUE THREAD

**Issue by lauracowen** [fraz3alpha/running-challenges#241]
Basically, challenges that can be done (or done best) by people who stay local (not necessarily at their home parkrun but large numbers of different parkruns are not a pre-requisite).

...

**Comment by rboyatt** [comment]
Very much support this idea.  Tourism is fun but we'd been thinking about different kinds of challenges that encouraged local running or volunteering - it had led me to implement #208 as a first idea.

**Comment by lauracowen** [comment]
#248

**Comment by mike-ology** [comment]
**Lucky Leap-year**

A badge for running parkrun on February 29th. Coincidentally, next weeks parkrun falls on that exact date!
...
Well, I just checked to see when the next Saturday, Feb 29th will occur and one would have to wait until 2048 for another chance to earn the badge (28 years!) - perhaps this is a little too exclusive :P

**Comment by fraz3alpha** [comment]
@mike-ology , we aren't going to add a leap year badge, see - https://twitter.com/RunChallenges/status/1226505808600539142?s=19

**Comment by mike-ology** [comment]
@fraz3alpha makes perfect sense to me!

Some other suggestions:
**Lucky 7's**: Run 3 consecutive parkruns with a time ending in '7' (e.g. three parkruns in a row 24:37, 31:17, 20:07 would qualify, and runs do not necessarily have to be at the same location or within 3 consecutive weeks).
**Crowd Control**: A 'bingo' themed badge which is earned by participating in 100 events, where each event has the number of participants ending in the numbers 00-99. Events with 54, 154 or 254 runners would all qualify to tick off the '54' number, so this should be achievable by most during their parkrun career.
**Best Buddies**: Complete X parkruns in a calendar year with the same runner either finishing immediately before or after you. Incentive for running with your partner or family, rather than running quickly. (I am not familiar with how data is collected, but I imagine this one might be a bit trickier to achieve given the necessary info isn't accessible from the main profile...)

**Comment by fraz3alpha** [comment]
@mike-ology , just for reference, the number of runners at an event, nor other runners at an event are obtainable in a sensible manner, so aren't something we'd be able to calculate anyway.
