### ISSUE TITLE
Safari Extensions

### ISSUE THREAD

**Issue by andydavidson** [fraz3alpha/running-challenges#272]
Thank you kindly for everything that you do for the community. <3

Is it possible to support Safari Extensions so that I can use the world's fastest browser with my favourite browser plugin? 

https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html

**Comment by fraz3alpha** [comment]
Not at this time, no.

**Comment by johnsyweb** [comment]
TIL https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

**Comment by fraz3alpha** [comment]
We've taken the decision to not take on any new work with this extension, so we are closing the issues that we know we'll likely never do, rather than having them being open and offering the chance of it being worked on. We'll keep fixing things that break, but I can't see us having any time to take on the extra effort of maintaining another platform
