### ISSUE TITLE
PB's to be recognised

### ISSUE THREAD

**Issue by DerekBlount** [fraz3alpha/running-challenges#35]
An Award for 10, 25, 50 PB's. An incentive for Tourists to visit more than once!

**Comment by fraz3alpha** [comment]
I'm in mixed minds about the concept of this one. 

I think it would be useful to track the number of PBs, and have added that as a suggestion under #8 where we would like to add some additional stats, but I think marking time progression isn't really in the ethos of "it's a run, not a race", and I wouldn't want to encourage more aggressive running to gain that important PB to get a badge. The important part that people are taking part and keeping active, not necessarily trying to get a PB week after week.

Personally I'd like people to return to a particular parkrun and volunteer rather than run every single week, and I think the volunteer badges seem to be going down rather well to get people into building that community.

There are already badges for 100 & 200 runs at a single parkrun, which are achievable by all if they become regulars at an event, no matter what ability, so I think those kinds of targets are the ones we want to encourage rather than speed based ones.

**Comment by fraz3alpha** [comment]
Implemented a counter via a stat, included in v0.5.0.11 - PR #63
